# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('published_date', models.DateField()),
                ('image_url', models.URLField(max_length=50)),
            ],
            options={
                'ordering': ['-published_date', 'title'],
            },
        ),
    ]
